### PR TITLE
fix: raw html output

### PR DESCRIPTION
**Pull request by zxqfox**

### CODE REVIEW

**Comment by zxqfox** [comment]
@mishanga It's a bug fix that we prbly need for supporting `escapeContent:true` in isl.
Guess nobody uses this bug as a feature (I'm actually don't see any chances to use it somehow).

**Comment by mishanga** [comment]
thanks!

**Comment by mishanga** [comment]
Выехало в v3.3.3

**Comment by zxqfox** [comment]
Спасибо ;-)

**Pull request merged**
