### PR TITLE
Fix bug with matchers order

### LINKED ISSUE #140: block vs. block_mod apply bug (order matters!)
BEMJSON
```javascript
{
    block: 'button',
    mods: {foo: true}
}
```

```javascript
bh.match('button_foo', function(ctx) {
   ctx.content('mod');
});

bh.match('button', function(ctx) {
   ctx.content('base');
});
```

Result HTML
```html
<div class="button button_foo">
base
</div>
```

Expected HTML
```html
<div class="button button_foo">
mod
</div>
```

**if you reorder bh.match() calls, everything works as expected.**

### PR DESCRIPTION
**Pull request by 1999**
fixes #140

### CODE REVIEW

**Comment by tadatuta** [comment]
now there's a way to manage priority by order (and one can use `{must,should}Deps` for that).
but with this patch there won't be any possibility to make block templates of more priority then it's modifiers. sure it's hard to find such real life examples but still now developer has control and afterward he won't have.

**Comment by 1999** [comment]
I'm pretty sure that [any] template engine (in fact, any library) must not depend on any other technology, such as deps from BEM. It should be a simple thing and work as expected without using any other libraries unless this is announced.

**Comment by zxqfox** [comment]
@1999 Then swap your matchers as I showed in #140. It's a talk about nothing.

**Comment by blond** [comment]
@1999 This change breaks the habitual behavior and can break a lot of existing code.

What problems are solved this PR? Could you give real examples?

**Comment by 1999** [comment]
@blond https://github.com/bem/bh/issues/140#issue-67565390

**Comment by mishanga** [comment]
Отписался в issue.

**Pull request closed without merging**
